### ISSUE TITLE
Error post instalacion

### ISSUE THREAD

**Issue by tXambe** [Hackplayers/Empire-mod-Hackplayers#6]
Hola,

Despues de la instalación al ejecutar empire sale el siguiente error:

Traceback (most recent call last):
  File "./empire", line 13, in <module>
    from lib.common import empire, helpers
  File "/opt/Empire-mod-Hackplayers/lib/common/empire.py", line 31, in <module>
    import agents
  File "/opt/Empire-mod-Hackplayers/lib/common/agents.py", line 68, in <module>
    import encryption
  File "/opt/Empire-mod-Hackplayers/lib/common/encryption.py", line 26, in <module>
    import M2Crypto
ImportError: No module named M2Crypto

El equipo es debian 9.8

**Comment by cybervaca** [comment]
Prueba a hacer un 
sudo pip install m2crypto

Ejecutaste el setup?

**Comment by tXambe** [comment]
Hola,

Al ejecutar el pip install me devuelve el siguiente error:

Failed building wheel for m2crypto

Y al final sale en rojo 

compilation terminated.
    error: command 'x86_64-linux-gnu-gcc' failed with exit status 1
------------------------------------------------------------------------

Command "/usr/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-install-XKLYAH/m2crypto/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-record-wjNSva/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-install-XKLYAH/m2crypto/

Me he descargado ese paquete lo he instalado , vuelto a lanzar el setup , no da errores y ahora al lanzar empire:

Traceback (most recent call last):
  File "./empire", line 1381, in <module>
    main = empire.MainMenu(args=args)
  File "/opt/Empire-mod-Hackplayers/lib/common/empire.py", line 79, in __init__
    (self.isroot, self.installPath, self.ipWhiteList, self.ipBlackList, self.obfuscate, self.obfuscateCommand) = helpers.get_config('rootuser, install_path,ip_whitelist,ip_blacklist,obfuscate,obfuscate_command')
TypeError: 'NoneType' object is not iterable


Un saludo y gracias por todo.

**Comment by tXambe** [comment]
Hola,

Ya esta chutando, he realizado un reset y ya arranca.

Un saludo

**Comment by cybervaca** [comment]
Perfecto, me alegro que te funcione ;)
